# Generated by Django 3.2.16 on 2022-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.CharField(default='2022', max_length=4, verbose_name='Рік створення'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Опис даного поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва поста'),
        ),
    ]
