# Generated by Django 3.2.16 on 2022-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221214_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.CharField(default='2022', max_length=4, verbose_name='Рік поблікації'),
        ),
    ]
